server:
  port: 5003

spring:
  datasource:
    url: jdbc:postgresql://localhost:5440/user_service?currentSchema=public
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 2
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        formatSql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: user-service


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:5004/eureka