

server:
  port: 5003

spring:
  datasource:
    url: jdbc:postgresql://localhost:5440/user_service?currentSchema=public
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 2
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
  application:
    name: user-service

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:5004/eureka/