server:
  port: 5006
spring:
  application:
    name: mail

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:5004/eureka
