server:
  port: 5001

spring:
  datasource:
    url: jdbc:postgresql://localhost:5440/user_service?currentSchema=public
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 2
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        formatSql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: none
    show-sql: true

  application:
    name: auth

  jwt:
    config:
      expiration-time-m-s: 360000
      type: signed

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:5004/eureka