server:
  port: 5001

spring:
  datasource:
    url: jdbc:postgresql://localhost:5440/user_service?currentSchema=public
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 2

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: none